### ISSUE TITLE
Support dynamic sorting

### ISSUE THREAD

**Issue by iulica** [juntagrico/juntagrico-webdav#7]
The files can be sorted by name or timestamp, but it is specified as a field in the server.

Sometimes, both ways of sorting could be helpful when trying to find a specific file.
I see two ways of implementing it, one is by giving parameters and doing the sorting on the server, another way would be to use javascript like tablesorter.

What do you think ?

**Comment by pascalfree** [comment]
juntagrico uses datatables.js to do that on most tables. The structure was actually already there, but the initialization was missing. fixed in #8
